icename: My To-Do App
version: 0.1.0
slug: my_todo_app
description: A simple to-do list application for Home Assistant.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ports:
  3000/tcp: 8080
build:
  context: .
  dockerfile: Dockerfile
