name: My To-Do App
version: 0.2.03
slug: my_todo_app
description: A simple to-do list application for Home Assistant
url: "https://github.com/mitchinator1/MULE-ToDo/tree/main/my_todo_app_addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 3000
panel_icon: mdi:format-list-checks
panel_title: My To-Do App
options:
  port_internal: 3000
  dark_mode: false
schema:
  port_internal: "int?"
  dark_mode: bool
environment:
  PORT: "[% port_internal %]" # Node.js will listen on this port (3000)
  DATABASE_PATH: "/data/todo.db" # This is a static path
build:
  context: .
  dockerfile: Dockerfile
