name: "Node.js To-Do API"
version: "1.0.0"
slug: "node_todo_api"
description: "A simple Node.js + SQLite to-do list API"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ports:
  3000/tcp: 3000
