name: "My To-Do App"
version: "1.0.0"
slug: "my_todo_app"
description: "Node.js + SQLite to-do app with frontend"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ports:
  3000/tcp: 3000
